import { NgModule } from '@angular/core';
import { NgIconsModule } from '@ng-icons/core';
import {
	octBookmark,
	octCodeOfConduct,
	octEye,
	octFileDirectory,
	octFileDirectoryOpenFill,
	octFileMoved,
	octGlobe,
	octGrabber,
	octListOrdered,
	octListUnordered,
	octLock,
	octPaintbrush,
	octRocket,
	octSearch,
	octShieldCheck,
	octStack,
	octCopy,
	octLinkExternal,
	octKebabHorizontal,
	octPlus,
	octPlusCircle,
	octTrash,
	octLink,
	octPencil,
	octHistory,
	octSliders,
	octPerson,
	octInbox,
	octInfo,
	octDatabase
} from '@ng-icons/octicons';

@NgModule({
	declarations: [],
	imports: [
		NgIconsModule.withIcons({
			octShieldCheck,
			octBookmark,
			octEye,
			octSearch,
			octFileMoved,
			octPaintbrush,
			octGlobe,
			octLock,
			octRocket,
			octCodeOfConduct,
			octStack,
			octListOrdered,
			octListUnordered,
			octGrabber,
			octFileDirectory,
			octFileDirectoryOpenFill,
			octCopy,
			octLinkExternal,
			octKebabHorizontal,
			octPlus,
			octPlusCircle,
			octTrash,
			octLink,
			octPencil,
			octHistory,
			octSliders,
			octPerson,
			octInbox,
			octInfo,
			octDatabase
		}),
	],
	exports: [NgIconsModule],
})
export class NgIconModule {}
