import { NgModule } from '@angular/core';
import { NgIconsModule } from '@ng-icons/core';
import {
	circumBookmark, circumCircleInfo, circumEdit, circumExport,
	circumFolderOff,
	circumFolderOn, circumHashtag, circumLogin, circumLogout, circumMaximize1, circumPalette, circumPower, circumSearch,
	circumSettings, circumSliderHorizontal, circumSquareMore, circumSquarePlus,
	circumTrash, circumUser,
	circumViewList
} from '@ng-icons/circum-icons';

import {
	octBookmark,
	octCodeOfConduct,
	octEye,
	octFileDirectory,
	octFileDirectoryOpenFill,
	octFileMoved,
	octGlobe,
	octGrabber,
	octListOrdered,
	octListUnordered,
	octLock,
	octPaintbrush,
	octRocket,
	octSearch,
	octShieldCheck,
	octStack,
	octCopy,
	octLinkExternal,
	octKebabHorizontal,
	octPlus,
	octPlusCircle,
	octTrash,
	octLink,
	octPencil,
	octHistory,
	octSliders,
	octPerson,
	octInbox,
	octInfo,
	octDatabase
} from '@ng-icons/octicons';

@NgModule({
	declarations: [],
	imports: [
		NgIconsModule.withIcons({
			octShieldCheck,
			octBookmark,
			octEye,
			octSearch,
			octFileMoved,
			octPaintbrush,
			octGlobe,
			octLock,
			octRocket,
			octCodeOfConduct,
			octStack,
			octListOrdered,
			octListUnordered,
			octGrabber,
			octFileDirectory,
			octFileDirectoryOpenFill,
			octCopy,
			octLinkExternal,
			octKebabHorizontal,
			octPlus,
			octPlusCircle,
			octTrash,
			octLink,
			octPencil,
			octHistory,
			octSliders,
			octPerson,
			octInbox,
			octInfo,
			octDatabase,
			
			circumFolderOff,
			circumFolderOn,
			circumTrash,
			circumViewList,
			circumBookmark,
			circumSettings,
			circumSquarePlus,
			circumSliderHorizontal,
			circumSearch,
			circumPower,
			circumPalette,
			circumMaximize1,
			circumHashtag,
			circumExport,
			circumCircleInfo,
			circumUser,
			circumLogin,
			circumLogout,
			circumSquareMore,
			circumEdit
		}),
	],
	exports: [NgIconsModule],
})
export class NgIconModule {}
